-- Herramientas de decisión del panel privado:
-- historial de precios y programación editorial por producto.
alter table public."Productos"
  add column if not exists campaign_name text,
  add column if not exists featured_from timestamptz,
  add column if not exists featured_until timestamptz,
  add column if not exists featured_priority integer not null default 0;

alter table public."Productos"
  drop constraint if exists productos_featured_priority_check;

alter table public."Productos"
  add constraint productos_featured_priority_check
  check (featured_priority between 0 and 10);

alter table public."Productos"
  drop constraint if exists productos_campaign_dates_check;

alter table public."Productos"
  add constraint productos_campaign_dates_check
  check (
    featured_from is null
    or featured_until is null
    or featured_until > featured_from
  );

create index if not exists productos_featured_schedule_idx
  on public."Productos" (featured_from, featured_until, featured_priority desc);

create table if not exists public.product_price_history (
  id bigint generated by default as identity primary key,
  product_id text not null,
  price numeric(14, 2) not null check (price > 0),
  currency_id text not null default 'ARS',
  price_source text not null default 'manual',
  change_reason text not null default 'sync',
  recorded_at timestamptz not null default now()
);

create index if not exists product_price_history_product_idx
  on public.product_price_history (product_id, recorded_at desc);

alter table public.product_price_history enable row level security;
revoke all on table public.product_price_history from anon, authenticated;
grant all on table public.product_price_history to service_role;

-- Punto inicial para los productos que ya existían antes del historial.
insert into public.product_price_history (
  product_id,
  price,
  currency_id,
  price_source,
  change_reason,
  recorded_at
)
select
  p.id::text,
  p.precio,
  coalesce(nullif(p.currency_id, ''), 'ARS'),
  coalesce(nullif(p.price_source, ''), 'manual'),
  'initial',
  coalesce(p.last_synced_at, p.created_at, now())
from public."Productos" p
where p.precio is not null
  and p.precio > 0
  and not exists (
    select 1
    from public.product_price_history h
    where h.product_id = p.id::text
  );
