-- Confirmaciones humanas de precios que Mercado Libre no entrega por API.
-- La fecha puede mostrarse en el panel, mientras que la identidad del
-- administrador queda en una tabla privada accesible sólo con service_role.
alter table public."Productos"
  add column if not exists manual_price_reviewed_at timestamptz;

create table if not exists public.product_manual_price_reviews (
  id bigint generated by default as identity primary key,
  product_id text not null,
  price numeric(14, 2) not null check (price > 0),
  currency_id text not null default 'ARS',
  reviewer_user_id uuid,
  reviewer_email text not null,
  reviewed_at timestamptz not null default now()
);

create index if not exists product_manual_price_reviews_product_idx
  on public.product_manual_price_reviews (product_id, reviewed_at desc);

alter table public.product_manual_price_reviews enable row level security;
revoke all on table public.product_manual_price_reviews from anon, authenticated;
grant all on table public.product_manual_price_reviews to service_role;

create or replace function public.clear_manual_price_review_on_change()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if coalesce(new.price_source, 'manual') = 'mercadolibre' then
    new.manual_price_reviewed_at := null;
  elsif old.precio is distinct from new.precio
    and new.manual_price_reviewed_at is not distinct from old.manual_price_reviewed_at then
    new.manual_price_reviewed_at := null;
  end if;

  return new;
end;
$$;

drop trigger if exists productos_clear_manual_price_review
  on public."Productos";

create trigger productos_clear_manual_price_review
before update of precio, price_source on public."Productos"
for each row
execute function public.clear_manual_price_review_on_change();

create or replace function public.confirm_manual_product_price(
  p_product_id text,
  p_price numeric,
  p_reviewer_user_id uuid,
  p_reviewer_email text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  reviewed_at_value timestamptz := now();
  updated_product public."Productos"%rowtype;
begin
  if p_price is null or p_price <= 0 then
    raise exception 'El precio manual debe ser mayor que cero.';
  end if;

  update public."Productos"
  set
    precio = round(p_price, 2),
    price_source = 'manual',
    price_needs_review = false,
    manual_price_reviewed_at = reviewed_at_value,
    sync_error = null
  where id::text = p_product_id
    and coalesce(price_source, 'manual') <> 'mercadolibre'
  returning * into updated_product;

  if not found then
    raise exception 'No se encontró un producto manual para confirmar.';
  end if;

  insert into public.product_manual_price_reviews (
    product_id,
    price,
    currency_id,
    reviewer_user_id,
    reviewer_email,
    reviewed_at
  )
  values (
    p_product_id,
    round(p_price, 2),
    coalesce(nullif(updated_product.currency_id, ''), 'ARS'),
    p_reviewer_user_id,
    lower(trim(p_reviewer_email)),
    reviewed_at_value
  );

  return to_jsonb(updated_product);
end;
$$;

revoke all on function public.confirm_manual_product_price(
  text,
  numeric,
  uuid,
  text
) from public, anon, authenticated;

grant execute on function public.confirm_manual_product_price(
  text,
  numeric,
  uuid,
  text
) to service_role;
