-- Preferencias editoriales propias de AH Tecno. category_id continúa guardando
-- la categoría original de Mercado Libre; categoria controla la navegación local.
alter table public."Productos"
  add column if not exists categoria text,
  add column if not exists is_visible boolean not null default true;

update public."Productos"
set ml_status = null
where trim(coalesce(ml_status, '')) = '';

update public."Productos"
set categoria = 'hogar-tecnologia'
where (categoria is null or categoria = '' or categoria = 'varios')
  and lower(coalesce(titulo, '')) similar to '%(aspiradora|robot aspirador|domotica|smart home)%';

create index if not exists productos_publication_state_idx
  on public."Productos" (is_visible, ml_status);

-- Medición mínima y respetuosa de la privacidad: producto, ubicación del botón
-- y momento del clic. No se guardan IP, correo, cookies ni datos del visitante.
create table if not exists public.product_outbound_clicks (
  id bigint generated by default as identity primary key,
  product_id text not null,
  source text not null check (source in ('card', 'modal', 'detail')),
  created_at timestamptz not null default now()
);

create index if not exists product_outbound_clicks_product_idx
  on public.product_outbound_clicks (product_id, created_at desc);

alter table public.product_outbound_clicks enable row level security;
revoke all on table public.product_outbound_clicks from anon, authenticated;
grant all on table public.product_outbound_clicks to service_role;

create or replace view public.product_click_totals as
select product_id, count(*)::bigint as clicks
from public.product_outbound_clicks
group by product_id;

revoke all on table public.product_click_totals from anon, authenticated;
grant select on table public.product_click_totals to service_role;
