-- Historial de disponibilidad. Un producto vencido se conserva para el panel
-- y las estadísticas, pero ml_status impide que vuelva a mostrarse al público.
alter table public."Productos"
  add column if not exists unavailable_since timestamptz,
  add column if not exists consecutive_sync_failures integer not null default 0;

alter table public."Productos"
  drop constraint if exists productos_consecutive_sync_failures_check;

alter table public."Productos"
  add constraint productos_consecutive_sync_failures_check
  check (consecutive_sync_failures >= 0);

update public."Productos"
set unavailable_since = coalesce(unavailable_since, last_synced_at, now())
where lower(trim(coalesce(ml_status, ''))) in
  ('closed', 'inactive', 'paused', 'under_review', 'not_found', 'deleted', 'expired');

-- La tabla nació para contar clics salientes. Se amplía sin borrar los datos
-- existentes para registrar también vistas de detalle y compartidos.
create table if not exists public.product_outbound_clicks (
  id bigint generated by default as identity primary key,
  product_id text not null,
  source text not null,
  created_at timestamptz not null default now()
);

alter table public.product_outbound_clicks
  add column if not exists event_type text not null default 'outbound_click';

alter table public.product_outbound_clicks
  drop constraint if exists product_outbound_clicks_source_check;

alter table public.product_outbound_clicks
  add constraint product_outbound_clicks_source_check
  check (source in ('card', 'modal', 'detail'));

alter table public.product_outbound_clicks
  drop constraint if exists product_outbound_clicks_event_type_check;

alter table public.product_outbound_clicks
  add constraint product_outbound_clicks_event_type_check
  check (event_type in ('outbound_click', 'product_view', 'share'));

create index if not exists product_outbound_clicks_event_idx
  on public.product_outbound_clicks (event_type, created_at desc);

alter table public.product_outbound_clicks enable row level security;
revoke all on table public.product_outbound_clicks from anon, authenticated;
grant all on table public.product_outbound_clicks to service_role;

create or replace view public.product_click_totals as
select product_id, count(*)::bigint as clicks
from public.product_outbound_clicks
where event_type = 'outbound_click'
group by product_id;

create or replace view public.product_event_totals as
select
  product_id,
  count(*) filter (where event_type = 'product_view')::bigint as product_views,
  count(*) filter (where event_type = 'outbound_click')::bigint as outbound_clicks,
  count(*) filter (where event_type = 'share')::bigint as shares
from public.product_outbound_clicks
group by product_id;

revoke all on table public.product_click_totals from anon, authenticated;
revoke all on table public.product_event_totals from anon, authenticated;
grant select on table public.product_click_totals to service_role;
grant select on table public.product_event_totals to service_role;
